### ISSUE TITLE
 Lost Art of Good Object Design/Nullo Pattern

### ISSUE THREAD

**Issue by bbrandt** [DevlinLiles/PresentationMaterials#1]
How do you feel about the Nullo pattern [recommended](http://structuremap.github.io/best-practices/) by [Jeremy](http://structuremap.github.io/resolving/try-getting-an-optional-service-by-plugin-type/) [Miller](http://codebetter.com/jeremymiller/2008/08/18/the-null-pattern-is-a-good-thing/), author of StructureMap?

I've been using the Null Object pattern for some time. Initially, after hearing your talk, I felt like the pattern contradicted the definition of an object, that it must define state and behavior.  Then I remembered that we are not using the pattern to define a new class without state or behavior.  We are instead defining state and behavior for a special instance of what is generally an already defined class.

Am I seeing it funny?

**Comment by bbrandt** [comment]
Yeah... so 10 minutes after asking this question I find myself about to define a class for DefaultStrategy or NullStrategy implementing an IStrategy.  I don't have a base class for the strategies and I don't have enough shared state and behavior to warrant creating one, so the base class would just be there to serve as the null object.

I know the code around where I'm working has some problems, so maybe I need to step back and look wider in my specific case.  But, how about the Nullo pattern in general?

**Comment by DevlinLiles** [comment]
The nullo pattern is typically a sign to me that I has missed something in the design, but there are cases where it makes sense. If I am implementing a visitor for instance, the behavior at a specific node may be to do nothing.

So, it depends, but tread carefully. If you find that you are doing this often, step back a level and see if there is a decision that you are delegating down and shouldn't be.

**Comment by bbrandt** [comment]
Thanks!
